// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozqpzwwpgyzlxhtekywj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96cXB6d3dwZ3l6bHhodGVreXdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMzM2OTQsImV4cCI6MjA3MDcwOTY5NH0.x3hxwdq36n7yfIOv3KUMMvJJyAMJYAwdOG3enbsR-3Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});